### ISSUE TITLE
Wrong project name

### ISSUE THREAD

**Issue by DLandDS** [PurpurMC/Tentacles#11]
https://github.com/PurpurMC/Tentacles/blob/a952a360a47602af39bba613de878689167bfbb3/settings.gradle.kts#L30

it's should be capital latter "Tentacles"

**Comment by encode42** [comment]
It shouldn't. I can't elaborate because I don't know why, but every server software that uses Paperweight does the same.

**Comment by DLandDS** [comment]
i cloned this template, applyPatch and loaded the gradle. it not detected Tentacle-API and Tentacle-Server module in intelij
but i changed it to capital letter and it solved.

**Comment by encode42** [comment]
https://github.com/PurpurMC/Purpur/blob/60dcdf0e44b3216b2f81d04ee8c65867384f17fd/settings.gradle.kts#L34

https://github.com/pufferfish-gg/Pufferfish/blob/f6a081a91041194dec01ab23bb24f27a3748e6e0/settings.gradle.kts#L8

https://github.com/PaperMC/Paper/blob/fe780d041ea2542c5e2c7ccbdfe7be38a84a85c7/settings.gradle.kts#L34

The submodules were likely detected by IntelliJ by the Gradle refresh, rather than this specific change.
