### ISSUE TITLE
Cannot update to purpur upstream

### ISSUE THREAD

**Issue by DLandDS** [PurpurMC/Tentacles#12]
![image](https://github.com/PurpurMC/Tentacles/assets/28994412/7e7d0793-ae0a-475f-bc4e-6e531749959d)

**Comment by encode42** [comment]
That is indeed what happens when upstream changes conflict with downstream patches. Don't get overwhelmed, though! If you have `wiggle` installed, then you can run the `apatch` script from within the affected submodule (`Server` in your case) which will attempt to do everything for you. If it fails, wiggle will show you what conflicts need to be manually resolved, in which you go about fixing a standard Git merge conflict.
